name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NX_VERBOSE_LOGGING: true
  NX_CLOUD_NO_TIMEOUTS: true
  NX_CLOUD_DEBUG_URLS: true
  NX_CLOUD_DTE_V2: true
  NX_CLOUD_ENVIRONMENT: 'development'
  NX_PERF_LOGGING: true
  NX_CI: true
  NX_WORKSPACE_DATA_DIRECTORY: ".nx/cache"
  NX_PROJECT_GRAPH_CACHE_DIRECTORY: ".nx/cache"
  NX_CLOUD_SKIP_WORKSPACE_DATA_CACHE: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      # Measure the computation of the project graph (cold)
      - name: Temporarily measure the computation of the project graph (cold)
        run: npx nx show projects

      # Measure the recomputation of the project graph (warm)
      - name: Temporarily measure the recomputation of the project graph (warm)
        run: npx nx show projects

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # Nx Affected runs only tasks affected by the changes in this PR/commit
      - run: npx nx affected -t lint test build e2e
